language: csharp
solution: LiveResults.Client.sln
install:
  - nuget restore LiveResults.Client.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release LiveResults.Client.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./LiveResults.Client.Tests/bin/Release/LiveResults.Client.Tests.dll